# Generated by Django 3.0.3 on 2020-02-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('hint3', models.TextField()),
                ('hint2', models.TextField()),
                ('hint1', models.TextField()),
                ('answer', models.TextField()),
                ('color', models.CharField(choices=[('B', 'Blue'), ('G', 'Green'), ('R', 'Red'), ('Y', 'Yellow')], max_length=10)),
            ],
        ),
    ]
